blank_issues_enabled: false
contact_links:
  - name: Syntax & Sips community discussions
    url: https://github.com/prashant-andani/Syntax-blogs/discussions
    about: Start a conversation or ask a question before opening an issue.
